### ISSUE TITLE
Possibility to save settings

### ISSUE THREAD

**Issue by daaanny90** [ahmadudin/electron-instaPy-GUI#1]
It's possible to implement the possibility to save the settings? It's not nice write every time the same things, and if the list of friends to exclude is longer than 10 names it's also frustrating.

**Comment by ahmadudin** [comment]
@daaanny90 actually its on top of my to-do list, should be available on next update

**Comment by daaanny90** [comment]
Really nice 👍 thanks for the fast answer.
