### ISSUE TITLE
Load button not found, working with current images!

### ISSUE THREAD

**Issue by daaanny90** [ahmadudin/electron-instaPy-GUI#2]
As the title says, when I set a hashtag and the number of likes to 50 for example, the program is unable to scroll down the page in order to show 50 pic and shows this error. If I use InstaPy from the terminal it works properly. If I use the GUI it shows this error message after a while.

**Comment by ahmadudin** [comment]
@daaanny90  interesting, what platform do you use?

**Comment by daaanny90** [comment]
I'm using Ubuntu 14.04 and I start the GUI just with `npm start` (I've globally installed electron). If you need other information just ask.

**Comment by ahmadudin** [comment]
ill try to reproduce the error later

**Comment by daaanny90** [comment]
I did other tests and I found that is not a problem of the GUI but of InstaPy itself. Or better, on which account you use InstaPy. With my account the scrolling looks disabled, but with another new account (or at least that never used InstaPy) the scrolling works properly. There is an issue open on the InstaPy page.
