### ISSUE TITLE
follow_user_followers() got an unexpected keyword argument 'random'

### ISSUE THREAD

**Issue by Marichka310** [ahmadudin/electron-instaPy-GUI#20]
Error: INFO - Session started - 2017-12-07 11:40:47 INFO - Logged in successfully! Traceback (most recent call last): File "quickstart.py", line 7, in <module> session.follow_user_followers(['utopia_8'], amount=30, sleep_delay=10, random=True, interact=False) TypeError: follow_user_followers() got an unexpected keyword argument 'random'

**Comment by timgrossmann** [comment]
@Marichka310 The InstaPy core argument changed to `randomize` to remove the problems with the internal `random` library...

I'll try to get that fixed ASAP, sorry for the problems

**Comment by Tonners15** [comment]
Any news on this fix Tim?

**Comment by timgrossmann** [comment]
@Tonners15 Sorry, no... 
I tried to contact @ahmadudin but it looks like he's heavily involved into his studies at the moment...

Maybe it will get fixed as soon as the new fixes in InstaPy are merged, then we can release a new version of the GUI with the newest version of InstaPy so people really have a waaaay better experience

**Comment by Tonners15** [comment]
Right on, thank you.

**Comment by ahmadudin** [comment]
Sorry guys, i am on a tight deadline right now, and i can't focus on different projects at the same time. I hope i can finish my project this month so i can back at this asap.

**Comment by Jenuan** [comment]
Any news on this fix??

**Comment by ahmadudin** [comment]
Solved by #23
