### ISSUE TITLE
No module named 'selenium'

### ISSUE THREAD

**Issue by preenupaul** [ahmadudin/electron-instaPy-GUI#29]
File "C:\Users\Rdr\Downloads\InstaPy-master\instapy\instapy.py", line 12, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by preenupaul** [comment]
i fixed it. thank you..

**Comment by timgrossmann** [comment]
@preenupaul Please close the issue and quickly mention how you fixed it.
Thank you

**Comment by preenupaul** [comment]
run the setup.py again then it fixed..
