### ISSUE TITLE
Won't let me select the InstaPy root nor close the GUI on Windows

### ISSUE THREAD

**Issue by StefanUPB** [ahmadudin/electron-instaPy-GUI#34]
I followed the instructions to download and install the GUI on Windows 10 64x. But when I start the GUI, I cannot select the InstaPy folder - nothing happens, when I click on the button. Same for the exit button (so I always have to kill it via the task manager). Other buttons and fields do work.

**Comment by ahmadudin** [comment]
@StefanUPB check #7 and please check on existing issues first before creating a new one, i am closing this.
