### ISSUE TITLE
Unable to do Unfollow

### ISSUE THREAD

**Issue by arisanguinetti** [ahmadudin/electron-instaPy-GUI#4]
Hi,

I'm unable to do unfollows, seems that the xpath has changed...
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[4]/div/div[2]/div/div[2]/div/div[2]"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.13.0-132-generic x86_64)

**Comment by ahmadudin** [comment]
please submit InstaPy issue to [InstaPy repo](https://github.com/timgrossmann/InstaPy).
