### ISSUE TITLE
Can't press "PATH" button

### ISSUE THREAD

**Issue by GalaxyLion** [ahmadudin/electron-instaPy-GUI#41]
When I press a button "PATH" nothing happens. And I can't close GUI, I have to kill the process through the task manager. What am I doing wrong? How can I fix it?

**Comment by AizenSousuke** [comment]
same issue here

**Comment by GalaxyLion** [comment]
I solved the problem. You need to go into the instapy folder, open powershell and enter "pip install." after "python setup.py install"

**Comment by kytwb** [comment]
@GalaxyLion I don't understand how this is related. The issue still exists on the build for macOS.
