### ISSUE TITLE
No space in comments

### ISSUE THREAD

**Issue by riadhrebei** [ahmadudin/electron-instaPy-GUI#44]
Hey folks,

All the comments my instagram account posts have no space in them. Example : Great shot! turns to Greatshot!

Any ideas ?

**Comment by faizalshuriken** [comment]
I have the same issue!

**Comment by animetrk** [comment]
Yes I have the same issue as well. I edited the quickstart.py and put spaces between the words but when I open the GUI again it deletes the spaces between words.

**Comment by webdesignkorenjak** [comment]
Same thing to me is hepening

**Comment by itisbeto** [comment]
Same here

**Comment by insolite** [comment]
Seems like that's because:
https://github.com/ahmadudin/electron-instaPy-GUI/blob/0020dc7f5da3610ebaa0682d6b95012a0c55c7c9/assets/js/app.js#L257-L258
