### ISSUE TITLE
chrome driver is missing for windows10 64bits

### ISSUE THREAD

**Issue by emyabdel** [ahmadudin/electron-instaPy-GUI#51]
hello

I run under windows 10 64 bits and i can find chrome driver just for 32 bits
i put the chromedriver 32 on asset and i run the InstaPy GUI app but always i get the message: chrome driver is missing. any solution?

**Comment by baaswietse** [comment]
Did you find a solution?

**Comment by emyabdel** [comment]
Used chrome driver 32bits it works

**Comment by baaswietse** [comment]
For me, I had to delete the .exe from the filename :)
