### ISSUE TITLE
Support Paste operation in fields

### ISSUE THREAD

**Issue by renjithn** [ahmadudin/electron-instaPy-GUI#6]
Environment - macOS, Is this currently supported? Links, Location Ids, Tags etc need to typed in, can't copy + paste.

Thanks for building this cool utility

**Comment by ahmadudin** [comment]
Actually, electron usage on macOS requires to manually set copy/paste keybindings. However, there is no macOS here so i am not aware of this issue, thanks for pointing it out.

Can you please help me to try this tweak and tell me if it works on macOS?

on main.js:
add
```javascript
const menu = require('electron')
```
and then change
```javascript
app.on('ready', createWindow)
```
to
```javascript
app.on('ready', () => {
  createWindow()
  if (process.platform === 'darwin') {
    var template = [{
      label: 'FromScratch',
      submenu: [{
        label: 'Quit',
        accelerator: 'CmdOrCtrl+Q',
        click: function() { app.quit(); }
      }]
    }, {
      label: 'Edit',
      submenu: [{
        label: 'Undo',
        accelerator: 'CmdOrCtrl+Z',
        selector: 'undo:'
      }, {
        label: 'Redo',
        accelerator: 'Shift+CmdOrCtrl+Z',
        selector: 'redo:'
      }, {
        type: 'separator'
      }, {
        label: 'Cut',
        accelerator: 'CmdOrCtrl+X',
        selector: 'cut:'
      }, {
        label: 'Copy',
        accelerator: 'CmdOrCtrl+C',
        selector: 'copy:'
      }, {
        label: 'Paste',
        accelerator: 'CmdOrCtrl+V',
        selector: 'paste:'
      }, {
        label: 'Select All',
        accelerator: 'CmdOrCtrl+A',
        selector: 'selectAll:'
      }]
    }];
    var osxMenu = menu.buildFromTemplate(template);
    menu.setApplicationMenu(osxMenu);
  }
})
```

**Comment by renjithn** [comment]
Thanks. Works like charm 👍  .   Just a small edit;

need to access menu as 'electron.Menu' from  [here](https://github.com/electron/electron/issues/5862)

 I've seen some other bugs with macOS which i'l report later. For now we are good.

**Comment by ahmadudin** [comment]
Great, thank you! Can't wait for your report.

**Comment by renjithn** [comment]
Couple of quick spots;
- Spaces within a comment sentence trimmed out (have a different parser function may be?)
- 'interact with followed user' (when used with "Follow user followers") with  doesn't seem to work properly ( Error: File "quickstart.py", line 7 session.set_user_interact(amount=, random=True, percentage=) ^ SyntaxError: invalid syntax)

**Comment by ahmadudin** [comment]
Yes, i haven't made parser for comments yet. The error on interact, did you fill the 'interact amount' field with non-number character? I forgot to make it only receive number input.

**Comment by ahmadudin** [comment]
Those bugs have been fixed, please let me know if you found another bug.
